### ISSUE TITLE
Super Game Module

### ISSUE THREAD

**Issue by gig71** [drhelius/Gearcoleco#11]
Would be Great to have SGM to play latest games released for this system.

**Comment by drhelius** [comment]
Yes, I'm planning to add support for it, but I don't have the time now. I will work on it next year.

**Comment by gig71** [comment]
Great !!!!
Thanks.

**Comment by theboy181** [comment]
Is it next year yet? all other emulators are not as nice as this one. :)

**Comment by Kelvfimer** [comment]
Yes it is needed super game master support!!!

**Comment by user23498723452** [comment]
Adding in my vote for this feature as well.  I am guessing bump posts like mine aren't exactly appreciated,  but not sure how to express support otherwise.

**Comment by drhelius** [comment]
SGM games that use normal cart and MegaCart are working now.

**Comment by KPreston2900050** [comment]
I just tested it a bit.
The Disassembler bounces around like old Christmas lights.

I haven't programmed for the SGM.  I'm wondering how the memory is mapped.
Is it the first 32k, replacing the Coleco BIOS when a cartridge is plugged in?

It's slightly confusing because you seem to have both running at one time.
Maybe have a toggle switch to choose which one to be mapped in?

This might be the reason why the disassembler is bouncing all over when an SGM cart is used.

**Comment by drhelius** [comment]
There is no need for a SGM toggle as it does not interfere with classic software. You have to explicitly enable RAM expansion, see [here](https://forums.atariage.com/topic/203851-super-game-module-technical-forum/).

Can you describe the 'bouncing' issue? I can't see any issue with the debugger. Maybe you are referring to ROM bank switching for MegaCart games? The debugger now shows you in which ROM bank the code is.
