### ISSUE TITLE
Keypad numbers 9 and 0 not implemented

### ISSUE THREAD

**Issue by NixieLake** [drhelius/Gearcoleco#25]
There's no way to map keypad numbers 9 or 0 from the standard controller. This should be a relatively simple matter, since there are already all the other controls available to map. This removes from playable games anything that uses two of the buttons on the main keypad, so I would suggest making this a higher priority.

In particular, I'm trying to play 2010: Graphical Action Game and I can't make the ship take off, because that's done by pressing 0 on the keypad.

**Comment by NixieLake** [comment]
I'm using the libretro core in RetroArch on Windows 11. 1.10.3 - Gearcoleco 1.0.1

**Comment by drhelius** [comment]
Thanks for reporting

**Comment by chomwitt** [comment]
Hi. I tried Gearcoleco with AmberElec . It's working whereas blueMSX cant load anything.
But aas @NixieLake commented and as i checked in **WarGames** the keypad doesnt seem to work although the config look sane (they map numbers 1-6 and 8 , # , *  to various buttons of my handheld.
So congratulation for Gearcoleco but if you have time take a look .

**Comment by user23498723452** [comment]
I'm also interested in gaining the ability to control these 2 buttons.  In the meantime, I found that pressing '1' on my keyboard entered 0 (zero) and pressing '2' entered 9.    FYI, as I have a smaller keyboard  that lacks the numpad, these are over the letters.

**Comment by drhelius** [comment]
There is a limitation in RetroArch where only 16 input buttons can be mapped to something you can later remap.

I addition, I'm working into adding blue and purple buttons of the Super Action Controller. So, all in all, you'll have a total of 20 input buttons. Because of the limitation 4 will need to be hard mapped. 

0 and 9 are currently hard mapped to keyboard keys "1" and "2" for Player 1 and "3" and "4" for Player 2.

A workaround could be mapping these 4 buttons to analog sticks but this would be quite weird.

**Comment by drhelius** [comment]
I ended up mapping "0", "9", "Purple" and "Blue" buttons to analog sticks by default.
Now you can change this mapping inside Retro Arch.
I will possible add an option to map this buttons to keyboard too.
