### ISSUE TITLE
Contacting you

### ISSUE THREAD

**Issue by KPreston2900050** [drhelius/Gearcoleco#40]
GITHUB doesn't have PM that I could find and I am not on twitter

Some really nasty things have happened to my family within the last six months and I  have been lashing out.
This emulator is not the forum for such things but here we are.

In any case.
How much of a one time contribution would it be to add ADAM support.
come up with a reasonable number and we can go from there.

It has to have all the features to include exchanging the BIOS, drives (ddp and disk), expansion ports and proper addressing.
Also for the Colecovision side, the ability to map in more than the 1k for up to 32k expansion boards.

Your latest release

The mouse pointer sits overtop the playfield, it doesn't disappear so it blocks everything.
Suggestion to have the mouse disappear and reappear with maybe the middle mouse button?
Even with the sensitivity in either end of the spectrum the mouse pointer does wander off screen and the onscreen player stutters.

The downside is that with CoolCV he overcame the mouse issue by locking the mouse to the emulator 100% which you have to press an F key to release or engage it.  I'm thinking the suggestion above to have  the middle mouse button do something similar while also turning off the mouse pointer.

Maybe the ability to map the Fire Buttons to the  Roller Controller?

Other than, great work

**Comment by drhelius** [comment]
Sorry to hear about your family. I hope you get well soon. 

I don't accept contract work. I see every donation, recurring or one shot, as a thanks for the work already done but not as a commitment for future work as this is my hobby. It is explained in my sponsors page. Please do not donate thinking that it will help the development of an specific new feature. I will never commit to specific features. 

Regarding this issue an PM don't worry, but I'm moving the issue to the correct repo as it was created on Gearboy.

Regarding the Adam, it will probably not happen as I'm not interested on this hardware and I want to move to the development of a new emu. The original intent for this emulator was the classic Colecovision console. 

Having said that and due to its popularity, I'm working on SGM. So RAM expansion is almost done but not commited yet. I'm already working on AY-3-8910A sound chip. 

I'm also working on MegaCart and Activision carts support right now as these usually come together with SGM games. 

I will open new issues with the rest of the features you are proposing (mouse) which I were already aware and find quite necessary.

Thanks for the help.

**Comment by drhelius** [comment]
Just committed my current work on SGM #11.
I created new issues for the features discussed #41 #42 #43 #44 #45.
I'm closing this issue as you can track them on their own issue.

If you want to create new issues/features feel free to do so.
If you want to discuss general things you can still use this issue without reopening again and we will receive notifications.
Thanks!
