### ISSUE TITLE
Colecovision SGM Help

### ISSUE THREAD

**Issue by JDraugr** [drhelius/Gearcoleco#52]
Hello.

How do you get Colecovision SGM files working on the Windows version of Gearcoleco? I downloaded the original coleco.rom bios file as well as the BIOS_XP.ROM which is supposed to be the SGM bios. When I try to load a SGM game I either get the typical insert a cartridge message or something like "This game requires the SGM module".

If anyone can help me sort this out I'd appreciate it.

Thanks,
John
PS: I'm hoping to use the libretro version eventually through RetroArch on a Windows PC so if there is anything different required to get SGM games running on the Gearcoleco libretro version, please let me know that as well..

**Comment by drhelius** [comment]
If you are running Retro Arch in any platform you just have to use the core downloader to get the latest version of the core. In RetroArch the core is updated to the latest commit in the 'main' branch. 

If you want to use the desktop version you can grab the latest executable from the latest commit build, as I still haven't published a recent release because I'm finishing some features before:

https://github.com/drhelius/Gearcoleco/actions/runs/7597913160

**Comment by JDraugr** [comment]
Thanks. :)
