### ISSUE TITLE
Gamepad not working in Atari VCS PC Mode USB

### ISSUE THREAD

**Issue by bwddppmm** [drhelius/Gearcoleco#56]
Hi. Working great have some games playing with keyboard but I’ve plugged in numerous joysticks like Xbox one, ps4, Atari vcs modern controller but none of them work. What am I doing wrong?? Running this in Debian from Atari VCS pc mode usb drive.
Thanks!!!!

**Comment by drhelius** [comment]
Sorry, I don't know.

You can look at the "About" window inside the emulator to see if the controller is really detected or not.

I'm using SDL2 for reading gamepad data so it's maybe an issue with SDL and Atari VCS PC mode because is working in at least 4 linux distros I tested, including Debian on a regular laptop.
